In [14]:
import tensorflow as tf
print(tf.__version__)

2.20.0

In [15]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [16]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [17]:
import tensorflow as tf
import numpy as np
import time

print(f"TensorFlow Version: {tf.__version__}")
print("---" * 10)

# 1. Check for GPU
gpu_devices = tf.config.list_physical_devices('GPU')
if gpu_devices:
    print(f"‚úÖ Found GPU: {gpu_devices[0].name}")
else:
    print("‚ùå WARNING: No GPU found. TensorFlow will use the CPU.")

print("---" * 10)
print("Running a simple model to test GPU acceleration...")

# 2. Create some dummy data
# 1000 samples, 10 features
X_train = np.random.rand(1000, 10).astype(np.float32)
# 1000 samples, 1 output
y_train = np.random.rand(1000, 1).astype(np.float32)

# 3. Build a simple Keras model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation='relu', input_shape=(10,)),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(1)
])

model.compile(optimizer='adam', loss='mean_squared_error')

# 4. Train the model
# This is the step that will use your GPU!
start_time = time.time()
model.fit(X_train, y_train, epochs=1)
end_time = time.time()

print("---" * 10)
print(f"üéâ Model training finished in {end_time - start_time:.2f} seconds.")
print("If the time was very fast (under 1-2 seconds), your GPU is working!")

TensorFlow Version: 2.20.0
------------------------------
‚úÖ Found GPU: /physical_device:GPU:0
------------------------------
Running a simple model to test GPU acceleration...

/home/mors/Desktop/Code/Ai-Ml/pandas/env/lib/python3.13/site-packages/keras/src/layers/core/dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

32/32 ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 5s 54ms/step - loss: 0.1038
------------------------------
üéâ Model training finished in 4.64 seconds.
If the time was very fast (under 1-2 seconds), your GPU is working!

In [18]:
what_to_do = {"0. An end-to-end Scikit-Learn workflow",
    "1. Getting the data ready",
    "2. Choose the right estimator/algorithm for our problems",
    "3. Fit the model/algorithm and use it to make predictions on our data",
    "4. Evaluating a model",
    "5. Improve a model",
    "6. Save and load a trained model",
    "7. Putting it all together!"}

In [19]:
heart_disease = pd.read_csv("heart-disease.csv")
heart_disease.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [23]:
X = heart_disease.drop("target", axis=1)
Y = heart_disease["target"]

In [24]:
x.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2

In [25]:
full_dataset = tf.data.Dataset.from_tensor_slices((X.values, y.values))

In [28]:
dataset_size = len(heart_disease)
train_size = int(0.8 * dataset_size)
test_size = dataset_size - train_size

full_dataset = full_dataset.shuffle(buffer_size=dataset_size, seed=42)

train_dataset = full_dataset.take(train_size)
test_dataset = full_dataset.skip(train_size)

batch_size = 32

train_dataset = train_dataset.batch(batch_size)
test_dataset = test_dataset.batch(batch_size)


print("--- Split using .take() and .skip() ---")
print(f"Total samples: {dataset_size}")
print(f"Training samples: {train_size}")
print(f"Test samples: {test_size}")
print(f"Training dataset: {train_dataset}")
print(f"Test dataset: {test_dataset}")

--- Split using .take() and .skip() ---
Total samples: 303
Training samples: 242
Test samples: 61
Training dataset: <_BatchDataset element_spec=(TensorSpec(shape=(None, 13), dtype=tf.float64, name=None), TensorSpec(shape=(None,), dtype=tf.int64, name=None))>
Test dataset: <_BatchDataset element_spec=(TensorSpec(shape=(None, 13), dtype=tf.float64, name=None), TensorSpec(shape=(None,), dtype=tf.int64, name=None))>